import { test, expect } from '@playwright/test'

test('runner can log an extra run and see it in history', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('button', { name: 'Continue as Raunaq' }).click()
  await expect(page.getByText('Rest day')).toBeVisible()
  await page.getByRole('link', { name: 'Log an extra run' }).click()
  await page.getByLabel(/Distance/).fill('6.2')
  await page.getByLabel(/Time/).fill('33:42')
  await page.getByRole('button', { name: 'Moderate' }).click()
  await page.getByRole('button', { name: 'Save run' }).click()
  await page.getByRole('link', { name: 'History' }).click()
  const historyEntry = page.getByRole('article')
  await expect(historyEntry).toContainText('6.2 KM')
  await expect(historyEntry).toContainText('5:26 /KM')
})

test('runner can make up Friday’s workout on Saturday', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('button', { name: 'Continue as Raunaq' }).click()
  await page.goto('/log?date=2026-08-01')
  await page.getByLabel(/Distance/).fill('4.5')
  await page.getByLabel(/Time/).fill('30:00')
  await page.getByRole('radio', { name: /Fri, 31 Jul.*Easy \+ Strides/ }).check()
  await page.getByRole('button', { name: 'Save run' }).click()
  await page.goto('/plan')
  await expect(page.getByLabel('Made up from Friday')).toBeVisible()
  await page.goto('/history')
  await expect(page.getByRole('article').filter({ hasText: 'Easy + Strides' })).toContainText('Made up from Friday')
  await page.goto('/progress')
  await expect(page.getByText('Raunaq due runs').locator('..')).toContainText('1/3')
  await page.goto('/history')
  const historyEntry = page.getByRole('article').filter({ hasText: 'Easy + Strides' })
  await historyEntry.getByRole('button', { name: 'Delete run' }).click()
  await expect(page.getByText('Run removed.')).toBeVisible()
  await page.getByRole('button', { name: 'Undo' }).click()
  await expect(page.getByRole('article').filter({ hasText: 'Easy + Strides' })).toContainText('Made up from Friday')
})

test('runner cannot assign a run after the plan week ends', async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('button', { name: 'Continue as Raunaq' }).click()
  await page.goto('/log?workout=w1-strides&date=2026-08-03')
  await expect(page.getByRole('alert')).toContainText('by Sunday')
})
